language: node_js
branches:
  except:
  - gh-pages
sudo: true
dist: trusty
before_script:
  - npm install -g bower t2ym/polymer-cli#wct6-plugin t2ym/web-component-tester-istanbul#0.10.1-wct6.11
  - export PATH=$PWD/node_modules/.bin:$PATH
  - polymer install --variants
env:
  global:
    secure: "MjAr2RM8GPvhpeCNiPVY9Ex/gk+PxbxyayIRyLZUelr5XWNctSBPHyyGo+ehrZpiL0Yn3Yg1XfFilrc8e7t04ci9HYDccUJswHRx7C4m4GJr37Gy3WPZ0tMa3T9QZP8JvjuAg84AomG/Be47lc96iG894/+nyvjFO9j1Mh90Jyi0QBEENHLLN8LfNs22F7exmb8UvcpMO/dLj210FgY9nDCCkcvLsL/FKln9h430+K06ARHDrgDVlc5gUdHPfDTDYUnzFT1eDHxd+5to2VOyAE4nmw6f1p9g3K56ojRffO8VSov90zxkZm7IGWe9no5jkhU4W26Bdrf900ZFBLS+GAOqzl7oGkCKROUVxj4YJ7ep90oBogDfbqiiBDG7KzB7G9D7fgHo6USGCBvm6qcn/yzWyUMgMPwD7IFPZM6Zax4uWnJf1DeJkTDxNUsQblU3m3MtzWjMZqt6nV/uleW+ozKqeMH7yB233JnKYKyno5aLYUyFScrYeI6B+tvFICEFBBzmtdjNwysGoBehlu++k4Rmh9QKYA46BtiSSMkVlACej1kbctWB9yK0hb/+gk7Dj41oYCLPY9OEbyka8UqTkzkL2tYNbZs6WdIr7iqZDbUvhv2pBtmgwe6A0l1CIbYhLEH+ZgHWdwpU9wcn/w9Rua3cjW1/JYiqLuWa7VY0yVs="
    secure: "j5pulZwX9GMIsgCkdqSAHGpCpqsbLBWFio2Xu78hMe8Oi1P7Qqo+JyRRUKtIVFGG/MZpi3itz9/njlrPemGtBShmcQdBCG7WpwsnQ55hPqgP61vsy/FHWb0i/AOrvKOMl2eXLriwRiMtnQ7Fc/zScHTe5Y4nSSh3vPUp8tLgN//8eiQAtIcsvVczCek8Z7Lfj79pmpf1OWCfxcpsCLwtkkg45BadlBGTX00GoBCxRo4U+A1/512Ad4xd+fVKwdw2RzWIsohijBPPkxAyVgtpW4haYSjxHef56tN93oFH5EyNnxmv5oUhJHXkMQyKvwO5/9KzvfodRcouiGRuN/HzdweAUkqslwIhfl2Yrxf1dzi6Q4FqwIwJ1JNsQSWv6wdYzlSlilY7sIL0mYVOB9HbdnMOp2dzgjkLyYnrTH2NzCsYyBpzNxqzc/5+VNsZwEQO53HhBjjYPepQYACRtJgiROsuRLqVuhLMyT98G7bE1KyAgqzN+46IHAPeMXmKo73sWbWRuTBRpI3QUqfDMIsSH2urYgZe3P9jws/xq2YHQRGne2Sq2qE+6I3SVOx0Sj7XDO68GU6hnmXvftwhawzF2dSxfp9EHYv6pEEliujU1uzYgqMrcpNbIFLFgbL7q8Jj5osXpEn17s1Ipg79bAg+S6V71PbrHl6YbJ54EYrYG0M="
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test
  - if [ "${TRAVIS_BRANCH}" != "" ]; then lcov-result-merger 'test/coverage-report*/lcov.info' | ./node_modules/coveralls/bin/coveralls.js || echo success; fi
